### ISSUE TITLE
Can we remove this repository?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-graphemes#5]
Does it contain anything valuable? It had a very short lifetime so if it contains only things which we can be easily recreated, I'd like to remove it.

cc @scofalik

**Comment by scofalik** [comment]
This repository was created when I was working on unicode support. It contains algorithms that better support graphemes. I wouldn't say it will be easy to recreate. But AFAICS it is pretty outdated. We never included it in the default build because it is heavy (it contains definitions of all graphemes).

**Comment by Reinmar** [comment]
Hm... so let's leave this. This is a topic which may return.
